add script to get wttr.in

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,5 +12,37 @@ jobs:
         run: pwd
       - name: Run a multi-line script
         run: |
-          ls
-          git status
+          FILE=./docs/assets/data/`date +"%Y%m%d-%H%M"`.csv
+          if [ -f "$FILE" ]; then
+              echo "$FILE exists. Done for today."
+          else
+
+              echo "Begin to get today's weather condition."
+              url="https://wttr.in/Den%20Haag?lang=de&format=%c,%C,%x,%h,%t,%f,%w,%l,%m,%M,%p,%P,%u,%D,%S,Z,%s,%d,%T,%Z"
+              response=$(curl -f $url)
+              status=$?
+              if [ $status -eq 0 ]; then
+                  echo $response > $FILE
+                  echo "$FILE saved."
+                  echo `date +"%Y%m%d-%H%M"` >> ./docs/assets/data.txt
+              else
+                  echo "curl exit code: ($status) $response"
+                  exit $status
+              fi
+          fi
+      - name: git check in
+        env:
+          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
+          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
+        run: |
+          git config user.email "$GIT_OWNER_EMAIL"
+          git config user.name "cblte"
+          if [[ `git status --porcelain` ]]; then
+            git add .
+            git commit -a -m "add weather data"
+            git remote rm origin
+            git remote add origin https://cblte:$PUSH_TOKEN@github.com:cblte/wttr-tracker.git
+            git push origin HEAD:main
+          else
+            echo 'unable to detech changes'
+          fi
